server:
  # 端口号范围 0-65535
  port: 9090
spring:
  application:
    name: admin-servers
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        # 暴露所有的监控断点
        include: '*'
