server:
  port: 8080  # \u5BA2\u6237\u7AEF\u7684\u7AEF\u53E3\u6CA1\u6709\u8981\u6C42

spring:
  application:
    name: eureka-client-a

# \u6CE8\u518C\u7684\u542B\u4E49\u5C31\u662F\u5C06\u81EA\u5DF1\u7684\u4FE1\u606F\u53D1\u9001\u7ED9eureka\u6CE8\u518C\u4E2D\u5FC3
eureka:
  # 客户端的相关配置
  client:
    # 指定注册的地址
    service-url:
      defaultZone: http://localhost:8761/eureka
      # 可以不向eureka-server中注册
    register-with-eureka: true
    # 配置应用是否拉取注册中心的服务列表到本地
    fetch-registry: true
    # 为了缓解服务列表的脏读问题 每隔30s拉取一次 性能消耗大
    registry-fetch-interval-seconds: 10
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5

