server:
  port: 8080
spring:
  application:
    name: teacher-login-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mtdatabases?allowPublicKeyRetrieval=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: "082916"

  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: "082916"
    database: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
