server:
  port: 8081

spring:
  application:
    name: eureka-client-b

eureka:
  client:
    service-url: # eureka\u670D\u52A1\u7AEF\u548C\u5BA2\u6237\u7AEF\u4EA4\u4E92\u7684\u5730\u5740
      defaultzone: http://localhost:8761/eureka
